### ISSUE TITLE
Setup on Colab

### ISSUE THREAD

**Issue by Mariam-73** [mesutpiskin/id-card-detector#41]
Hey!
I'm unable to run it on Google Colab

WARNING:tensorflow:From id_card_detection_image.py:53: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

WARNING:tensorflow:From id_card_detection_image.py:59: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2021-08-11 07:59:44.140550: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-08-11 07:59:44.153485: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-08-11 07:59:44.153542: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (746494ea7a87): /proc/driver/nvidia/version does not exist
2021-08-11 07:59:44.153966: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-08-11 07:59:44.159911: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200140000 Hz
2021-08-11 07:59:44.160127: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x559ad0e3a680 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-08-11 07:59:44.160160: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
: cannot connect to X server

**Comment by eyad-py** [comment]
Google colab crashes if you try to display an image using cv2.imshow() you can change it with cv2_imshow()

from google.colab.patches import cv2_imshow
cv2_imshow(image)
this works for me
